"""add signed_file_path to documents

Revision ID: 0165838914a1
Revises: 97ce47b50ba3
Create Date: 2026-08-25 12:25:13.657310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0165838914a1'
down_revision: Union[str, None] = '97ce47b50ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('signed_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'signed_file_path')
    # ### end Alembic commands ###
