"""add file_data and signed_file_data for persistent storage

Revision ID: 1c937ba31dfe
Revises: 0165838914a1
Create Date: 2026-08-29 14:26:08.692469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c937ba31dfe'
down_revision: Union[str, None] = '0165838914a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('documents', sa.Column('signed_file_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'signed_file_data')
    op.drop_column('documents', 'file_data')
    # ### end Alembic commands ###
