"""add review_note to extracted_fields

Revision ID: 97ce47b50ba3
Revises: 83188bcfd397
Create Date: 2026-08-24 17:06:01.865364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ce47b50ba3'
down_revision: Union[str, None] = '83188bcfd397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_fields', sa.Column('review_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_fields', 'review_note')
    # ### end Alembic commands ###
