"""add file_data and signed_file_data for persistent storage

Revision ID: f3ded9df0483
Revises: 1c937ba31dfe
Create Date: 2026-08-29 14:31:16.771541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ded9df0483'
down_revision: Union[str, None] = '1c937ba31dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
